image: Visual Studio 2019

build:
  publish_nuget: true
  #on:
  #  branch: dev

nuget:
  project_feed: true

build_script:
  - cmd: dotnet build
  - cmd: dotnet test
  - cmd: dotnet pack

after_build:
  - ps: Get-ChildItem .\bin\packages\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
